stages:
  process_data:
    cmd: python src/data_processing/process_data.py
    deps:
    - data/raw
    - src/data_processing/process_data.py
    outs:
    - data/processed/classcount.json
    - data/processed/data.json
    - data/processed/meta_data.json
    - data/processed/observations.csv
  nmds:
    cmd: python src/data_processing/nmds.py
    deps:
    - data/processed/data.json
    - data/processed/meta_data.json
    - src/data_processing/nmds.py
    outs:
    - data/model/nmds.json
    params:
    - nmds.random_seed
  rost:
    cmd: python src/data_processing/rost.py
    deps:
    - data/processed/observations.csv
    - data/processed/meta_data.json
    - src/data_processing/rost.py
    - data/preserved_rost_output/rost_topic_prob.json
    - data/preserved_rost_output/rost_wt_matrix.json
    - data/preserved_rost_output/rost_word_prob.json
    outs:
    - data/model/rost_topic_prob.json
    - data/model/rost_wt_matrix.json
    - data/model/rost_word_prob.json
    params:
    - rost.epochs
    - rost.k
    - rost.alpha
    - rost.beta
    - rost.overwrite
    - rost.copy_preserved_data
  figure1:
    cmd: python src/outputs/figure1.py
    deps:
    - data/processed/meta_data.json
    - data/raw/altitude.csv
    - data/raw/sst.csv
    - data/raw/ec.csv
    - src/outputs/figure1.py
    - src/outputs/common.py
    outs:
    - output/figure1.eps
    params:
    - figures.page_width
    - figures.page_height
    - figures.dpi
  figure3:
    cmd: python src/outputs/figure3.py
    deps:
    - data/processed/meta_data.json
    - data/model/nmds.json
    - src/outputs/figure3.py
    - src/outputs/common.py
    outs:
    - output/figure3.eps
    params:
    - figures.page_width
    - figures.page_height
    - figures.dpi
  figure4:
    cmd: python src/outputs/figure4.py
    deps:
      - data/processed/meta_data.json
      - data/model/rost_topic_prob.json
      - src/outputs/figure4.py
      - src/outputs/common.py
    outs:
      - output/figure4.eps
    params:
      - figures.page_width
      - figures.page_height
      - figures.dpi
  figure5:
    cmd: python src/outputs/figure5.py
    deps:
      - data/processed/meta_data.json
      - data/model/rost_wt_matrix.json
      - src/outputs/figure5.py
      - src/outputs/common.py
    outs:
      - output/figure5.eps
    params:
      - figures.page_width
      - figures.page_height
      - figures.dpi
  figure6:
    cmd: python src/outputs/figure6.py
    deps:
      - data/processed/meta_data.json
      - data/model/rost_topic_prob.json
      - src/outputs/figure6.py
      - src/outputs/common.py
    outs:
      - output/figure6.eps
    params:
      - figures.page_width
      - figures.page_height
      - figures.dpi
  figure7:
    cmd: python src/outputs/figure7.py
    deps:
      - data/processed/meta_data.json
      - data/processed/data.json
      - data/model/rost_topic_prob.json
      - src/outputs/figure7.py
      - src/outputs/common.py
    outs:
      - output/figure7.eps
    params:
      - figures.page_width
      - figures.page_height
      - figures.dpi
  figure7_defense:
    cmd: python src/outputs/figure7_defense.py
    deps:
      - data/processed/meta_data.json
      - data/processed/data.json
      - data/model/rost_topic_prob.json
      - src/outputs/figure7_defense.py
      - src/outputs/common.py
    outs:
      - output/figure7_defense.png
    params:
      - figures.page_width
      - figures.page_height
      - figures.dpi
  figure8:
    cmd: python src/outputs/figure8.py
    deps:
      - data/processed/meta_data.json
      - data/processed/data.json
      - data/raw/summary_biovol_allHDF_min20_2021.classcount.csv
      - data/raw/summary_biovol_allHDF_min20_2021.meta_data.csv
      - data/raw/1dmodel.csv
      - src/outputs/figure8.py
      - src/outputs/common.py
    outs:
      - output/figure8.eps
    params:
      - figures.page_width
      - figures.page_height
      - figures.dpi
  table1:
    cmd: python src/outputs/table1.py
    deps:
      - data/processed/meta_data.json
      - data/model/rost_topic_prob.json
      - src/outputs/table1.py
      - src/outputs/common.py
    outs:
      - output/table1.tex
